### ISSUE TITLE
(MatchError) no match of right hand side value

### ISSUE THREAD

**Issue by mxdavis** [elixirkoans/elixir-koans#202]
Hi, 

Sorry if this is a very newbie question but I'm getting the below error:

```
[09:57:58] (master) elixir-koans
// ♥mix meditate
Compiling 2 files (.ex)
** (MatchError) no match of right hand side value: {:error, {:enoent, [{:erlang, :open_port, [{:spawn_executable, '/Users/malkadavis/projects/elixir-ko
ans/_build/dev/lib/exfswatch/priv/mac_listener'}, [:stream, :exit_status, {:line, 16384}, {:args, ['-F', '/Users/malkadavis/projects/elixir-koans/lib/k
oans']}, {:cd, "/var/folders/rf/lmzn3mh90ysg39fl6m43j4g40000gn/T/"}]], []}, {ExFSWatch.Worker, :init, 1, [file: 'lib/exfswatch/worker.ex', line: 12]},
{:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 365]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 333]}, {:proc_lib, :init_p_d
o_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
    (elixir_koans) lib/meditate.ex:10: Mix.Tasks.Meditate.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2
```

When I do mix test I get the below error:

```Generated elixir_koans app
.................................
10:00:49.538 [error] Process #PID<0.940.0> raised an exception
** (UndefinedFunctionError) function Equalities."We shall contemplate truth by testing reality, via equality"/1 is undefined or private. Did you mean o
ne of:

      * "We shall contemplate truth by testing reality, via equality"/0

    (elixir_koans) Equalities."We shall contemplate truth by testing reality, via equality"(true)
    (elixir_koans) lib/execute.ex:34: Execute.exec/4
n

  1) test Equalities (EqualitiesTests)
     test/koans/equalities_koan_test.exs:5
     ** (ExUnit.TimeoutError) test timed out after 60000ms. You can change the timeout:

       1. per test by setting "@tag timeout: x"
       2. per case by setting "@moduletag timeout: x"
       3. globally via "ExUnit.start(timeout: x)" configuration
       4. or set it to infinity per run by calling "mix test --trace"
          (useful when using IEx.pry)

     Timeouts are given as integers in milliseconds.

     code: test_all(Equalities, answers)
     stacktrace:
       (elixir_koans) lib/execute.ex:26: Execute.listen_for_result/2
       (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
       test/test_helper.exs:10: TestHarness.test_all/2
       test/koans/equalities_koan_test.exs:16: (test)
       (ex_unit) lib/ex_unit/runner.ex:292: ExUnit.Runner.exec_test/1
       (stdlib) timer.erl:166: :timer.tc/1
       (ex_unit) lib/ex_unit/runner.ex:240: anonymous fn/3 in ExUnit.Runner.spawn_test/3

```

**Comment by felipesere** [comment]
Hi! Thank you for reporting this. Both errors seem very interesting. 
I'm at work right now, but I might be able to take a look over lunch or sometime this evening. 

Am I right in assuming OSX?

**Comment by mxdavis** [comment]
Hmm I just ran `mix deps.get`, I guess I somehow overlooked that or thought I had done it. 

Now I have a different error but I may be able to fix this one 

```// ♥mix meditate
Compiling 2 files (.ex)

== Compilation error in file lib/koans/06_lists.ex ==
** (SyntaxError) lib/koans/06_lists.ex:23: unexpected token: " " (column 49, codepoint U+00A0)
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers
/1```

So I think I'm good, thanks so much!

**Comment by mxdavis** [comment]
Actually fixed that and getting same error :(

```Compiling 2 files (.ex)
** (MatchError) no match of right hand side value: {:error, {:enoent, [{:erlang, :open_port, [{:spawn_execu
table, '/Users/malkadavis/projects/elixir-koans/_build/dev/lib/exfswatch/priv/mac_listener'}, [:stream, :ex
it_status, {:line, 16384}, {:args, ['-F', '/Users/malkadavis/projects/elixir-koans/lib/koans']}, {:cd, "/va
r/folders/rf/lmzn3mh90ysg39fl6m43j4g40000gn/T/"}]], []}, {ExFSWatch.Worker, :init, 1, [file: 'lib/exfswatch
/worker.ex', line: 12]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 365]}, {:gen_server, :in
it_it, 6, [file: 'gen_server.erl', line: 333]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', lin
e: 247]}]}}
    (elixir_koans) lib/meditate.ex:10: Mix.Tasks.Meditate.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2```

On mac, and using elixir 1.5.1

**Comment by iamvery** [comment]
I wasn't able to completely isolate the issue, but a coupled things I noticed:

- The `MatchError` you're seeing appears to be a problem with the file-system watcher.
- The library we depend on (`exfswatch`) recently experienced a pretty big [rename and refactor](https://github.com/falood/file_system/pull/26).
- The second error (while attempting to run the tests) also appears as if it might be a file-system issue/oddity. I say that, because it's as if Elixir can't find the module to load.

Sorry for the vague comments. I'm short on time this morning, but I thought these observations might be useful to you all trying to narrow things down!

**Comment by mxdavis** [comment]
I'll take a look, thanks so much. For now I'm enjoying the challenges without running the tests ;)

**Comment by felipesere** [comment]
I updated my Elixir to 1.5.1 but I still could not get the error to happen.
What OTP are you running? I am running Erlang/OTP 20 from homebrew.
You can check with 
`erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell`

**Comment by mxdavis** [comment]
// ♥erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell
"20"

But I think it's fine I can complete the exercises with the use of IEX. Thanks so much for a wonderful tour of elixir.
