### ISSUE TITLE
Having problem with mix meditate

### ISSUE THREAD

**Issue by lukaleli** [elixirkoans/elixir-koans#211]
Hey, just fetched elixir koans, but I'm having issues with running it. I'm using elixir version 1.6.0-dev on Mac. Does the dev release of elixir affect it? Here's the console output:

```Shell
$ mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
  exfswatch 0.4.1
* Getting exfswatch (Hex package)
  Checking package (https://repo.hex.pm/tarballs/exfswatch-0.4.1.tar)
  Using locally cached package
$ mix meditate
==> exfswatch
[warning] Mix compiler :src was supposed to return :ok | :noop | {:ok | :noop | :error, [diagnostic]} but it returned 0
Compiling 8 files (.ex)
warning: Kernel.to_char_list/1 is deprecated, use Kernel.to_charlist/1
  lib/exfswatch.ex:9

warning: Kernel.to_char_list/1 is deprecated, use Kernel.to_charlist/1
  lib/exfswatch/utils.ex:5

Generated exfswatch app
==> elixir_koans
Compiling 33 files (.ex)
warning: String.ljust/2 is deprecated, use String.pad_trailing/2
  lib/display/progress_bar.ex:8

warning: Range.range?/1 is deprecated, instead pattern match on left..right
  lib/koans/03_numbers.ex:91

warning: Range.range?/1 is deprecated, instead pattern match on left..right
  lib/koans/03_numbers.ex:92

warning: no clause will ever match
  lib/koans/12_pattern_matching.ex:44

warning: the result of the expression is ignored (suppress the warning by assigning the expression to the _ variable)
  lib/koans/10_structs.ex:27

Generated elixir_koans app
** (FunctionClauseError) no function clause matching in Equalities.__info__/1

    The following arguments were given to Equalities.__info__/1:

        # 1
        :exports

    (elixir_koans) Equalities.__info__/1
    (elixir_koans) lib/runner.ex:5: Runner.koan?/1
    (elixir_koans) lib/meditate.ex:39: Mix.Tasks.Meditate.ok?/1
    (elixir_koans) lib/meditate.ex:14: Mix.Tasks.Meditate.run/1
    (mix) lib/mix/task.ex:315: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
```

**Comment by ukutaht** [comment]
@lukaleli Thank you for reporting. We just merged a patch for this, please pull from master and try again.

**Comment by mholubowski** [comment]
Hey! For anyone reading this, as of now (December 9th, 2017) `mix meditate` fails when using Elixir 1.5, but works just fine on 1.6.

**Comment by Nagasaki45** [comment]
Hi @mholubowski, I don't encounter any problem running `mix meditate` on elixir 1.5.2 on arch linux. Can you please elaborate?

**Comment by felipesere** [comment]
I just tried with 1.6.0 and 1.5.2 and both work for me. Please reopen with more details if this is still an issue.
