### ISSUE TITLE
Autoreload doesn’t work with unicode paths

### ISSUE THREAD

**Issue by Glutexo** [elixirkoans/elixir-koans#228]
If the _elixir-koans_ folder is located in a path with non-ASCII characters, the autoreloading doesn’t  work. An error like this is raised every time a change is detected:

```
** (Code.LoadError) could not load /Users/stomsa/_dev/Å/elixir-koans/lib/koans/02_strings.ex
    (elixir) lib/code.ex:1147: Code.find_file/2
    (elixir) lib/code.ex:713: Code.load_file/2
```

The path should be _~/_dev/ň/_ and not _~/_dev/Å/_.

Happens on macOS Mojave 10.14 (18A391) with zsh.

**Comment by iamvery** [comment]
I dug in a little bit on this. The error originates [here](https://github.com/elixir-lang/elixir/blob/eb5679bfcc9bd35c4c016e91745b4a1a4d43356a/lib/elixir/lib/code.ex#L1147). It ultimately seems that [`:elixir_utils.read_file_type`](https://github.com/elixir-lang/elixir/blob/887e8f2633b361200843924e597edf36d38d2ed9/lib/elixir/src/elixir_utils.erl#L66-L73) doesn't handle these characters well. I don't have time to dig in any further right now, but overall it feels like an Elixir/Erlang issue more than this specific project. That is unless there is some escaping or something special that needs to happen in order to support paths like this.

I did, however, notice a deprecated call which is fixed in #229.

**Comment by Glutexo** [comment]
Thanks for taking a look at this, @iamvery! I examined a bit too and I at least found out that the _Watcher’s handle_info_ [method](https://github.com/elixirkoans/elixir-koans/blob/6c53c51fed90107162139d61dc7bcfbf41171ed0/lib/watcher.ex#L14) already receive an already invalid path. Printing it out, the Unicode characters are already botched.

I wanted to dig deeper and see the actual result of _file_system’s parse_line_ [method](https://github.com/falood/file_system/blob/v0.2.2/lib/file_system/backends/fs_mac.ex#L172) for a Mac worker, but I wasn’t able to get my changes actually executed.

My impression is that the culprit lies somewhere there, not translating the platform-specific watcher result correctly. But maybe it’s even deeper.

**Comment by iamvery** [comment]
Fun times 😅
