### ISSUE TITLE
Trying to run mix deps.get throws an error for OTP 25

### ISSUE THREAD

**Issue by sharno** [elixirkoans/elixir-koans#274]
Elixir 1.13.x
erlang/OTP 25

```
PS C:\Users\sharno\projects\elixir-koans> mix deps.get

02:21:04.071 [error] beam\beam_load.c(551): Error loading function 'Elixir.Hex.Version':'allow_pre_available?'/0: op put_tuple u x:
  please re-compile this module with an Erlang/OTP 25 compiler



02:21:04.071 [error] Loading of c:/Users/sharno/.mix/archives/hex-0.21.2/hex-0.21.2/ebin/Elixir.Hex.Version.beam failed: :badfile


02:21:04.071 [info]  Application hex exited: exited in: Hex.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Hex.Version.start/0 is undefined (module Hex.Version is not available)
            (hex 0.21.2) Hex.Version.start()
            (hex 0.21.2) lib/hex/application.ex:12: Hex.Application.start/2
            (kernel 8.4) application_master.erl:293: :application_master.start_it_old/4

02:21:04.096 [info]  Application inets exited: :stopped

02:21:04.098 [info]  Application ssl exited: :stopped

02:21:04.098 [info]  Application public_key exited: :stopped

02:21:04.098 [info]  Application asn1 exited: :stopped

02:21:04.098 [info]  Application crypto exited: :stopped
Could not start Hex. Try fetching a new version with "mix local.hex" or uninstalling it with "mix archive.uninstall hex.ez"
** (MatchError) no match of right hand side value: {:error, {:hex, {:bad_return, {{Hex.Application, :start, [:normal, []]}, {:EXIT, {:undef, [{Hex.Version, :start, [], []}, {Hex.Application, :start, 2, [file: 'lib/hex/application.ex', line: 12]}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 293]}]}}}}}}
    (hex 0.21.2) lib/hex.ex:5: Hex.start/0
    (mix 1.12.2) lib/mix/hex.ex:59: Mix.Hex.start/0
    (mix 1.12.2) lib/mix/dep/loader.ex:194: Mix.Dep.Loader.with_scm_and_app/4
    (mix 1.12.2) lib/mix/dep/loader.ex:147: Mix.Dep.Loader.to_dep/3
    (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
    (mix 1.12.2) lib/mix/dep/loader.ex:364: Mix.Dep.Loader.mix_children/2
    (mix 1.12.2) lib/mix/dep/loader.ex:18: Mix.Dep.Loader.children/0
    (mix 1.12.2) lib/mix/dep/converger.ex:57: Mix.Dep.Converger.all/4
```

**Comment by sharno** [comment]
I removed `.mix` folder in the home directory and reran the command and it ran without errors
